# escape=`

ARG BASE_IMAGE
#ARG_SXA_IMAGE

#FROM_SXA_IMAGE
FROM ${BASE_IMAGE}

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

#SXA_Module